services:
  app:
    image: golang:tip-alpine3.20
    container_name: go_app
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: ["go", "run", "app/main.go"]
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: go_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

